# Generated by Django 4.2.5 on 2023-10-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ürünKodu', models.IntegerField(unique=True)),
                ('Adet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ürün',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productKod', models.IntegerField(unique=True)),
                ('productName', models.CharField(max_length=170)),
                ('imgUrl', models.CharField(max_length=210)),
                ('productInfo1', models.CharField(default='', max_length=240)),
                ('productInfo2', models.CharField(default='', max_length=240)),
                ('Fiyat', models.FloatField()),
                ('degerlendirme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SepetÜrün',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adet', models.IntegerField()),
                ('ürün', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ürünler', to='ürün_kontrol.ürün')),
            ],
        ),
    ]
